== How to you locally build an android apk from React Native

TODO: update with more instructions.
expo eject to get the React Native code


Update app/app.json:

```
```


=== exp detach

```
$ exp detach

An Expo user account is required to proceed.

? How would you like to authenticate? Log in with an existing Expo account
? Username/Email Address: asean
? Password: [hidden]

Success. You are now logged in as asean.
[06:10:18] Making sure project is set up correctly...
/[06:10:20] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[06:10:23] Your project looks good!
Validating project manifest...
You have not specified a custom scheme for deep linking. A default value of exp27ad9a7da403481d8ac434e657809b2b will be used. You can change this later by following the instructions in this guide: https://docs.expo.io/versions/latest/workflow/linking
Skipping iOS because you are not running macOS.
You'll need to specify an Android package name. See: https://docs.expo.io/versions/latest/guides/configuration.html#package
? What would you like your Android package name to be? com.asean.deteachdemo
Moving Android project files...
Downloading Android code...
Updating Android app...
{ buildPhase: 'running shell app modifications' } 'Warning: No config file specified.'
Cleaning up Android...
Android detach is complete!

Writing ExpoKit configuration...
Installing the Expo fork of react-native...
Installing react-native@https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz using yarn...

Finished detaching your project! Look in the `android` and `ios` directories for the respective native projects. Follow the ExpoKit guide at https://docs.expo.io/versions/latest/guides/expokit.html to get your project running.
```

== Build the container that will be used to build the apk 

```

docker build -t java8-android-localbuilder .

```

== Build the apk

prep:
.exp/settings.json (ref: https://github.com/react-community/create-react-native-app/issues/400, https://forums.expo.io/t/react-native-packager-hangs-proxy-related/4025)
```
  "urlRandomness": "null"
```


```
docker run --rm -it -v $PWD:/app react-native-android-builder:latest bash
```

once inside the docker container:

```
cd into the project
$ cd /app

# copy  kernel-manifest.json as  shell-app-manifest.json
cd android/app/src/main/assets
cp kernel-manifest.json shell-app-manifest.json


# Now cd into the android folder
$ cd /app/android

# build the app
$ ./gradlew assembleRelease

# Once the build is successful, you can find the apk in app/build/outputs/apk/ directory.
# eg: app-prod-release-unsigned.apk
```


== codebuild

```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock \
-e "IMAGE_NAME=localandroidbuild" -e "ARTIFACTS=/home/ec2-user/environment/artifacts" \
-e "SOURCE=/home/ec2-user/environment/01/myapp" amazon/aws-codebuild-local
```

buildspec.yml

```
version: 0.1
phases:
  build:
    commands:
      - cd android && ./gradlew assembleRelease
artifacts:
  files:
    - android/app/build/outputs/apk/app-prod-release-unsigned.apk

```



== WIP







```
`aws ecr get-login --no-include-email`

aws  ecr create-repository --repository-name java8-android-builder

```
You'll see:


```

{
    "repository": {
        "registryId": "XXXXXXXXXXX", 
        "repositoryName": "java8-android-builder", 
        "repositoryArn": "arn:aws:ecr:ap-southeast-1:XXXXXXXXXXX:repository/java8-android-builder", 
        "createdAt": 1534061289.0, 
        "repositoryUri": "XXXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/java8-android-builder"
    }
}
```


docker tag java8-android-localbuilder XXXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/java8-android-builder
docker push XXXXXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/java8-android-builder

Assign Codebuild the permission to pull this image.





CodeCommit

aws codecommit create-repository --repository-name jiojiome-mobile-app
```
{
    "repositoryMetadata": {
        "repositoryName": "jiojiome-mobile-app", 
        "cloneUrlSsh": "ssh://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/jiojiome-mobile-app", 
        "lastModifiedDate": 1534061690.066, 
        "repositoryId": "87b338a8-0726-45e3-9ba4-6a73e4f406f1", 
        "cloneUrlHttp": "https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/jiojiome-mobile-app", 
        "creationDate": 1534061690.066, 
        "Arn": "arn:aws:codecommit:ap-southeast-1:558477364476:jiojiome-mobile-app", 
        "accountId": "558477364476"
    }
}
```

create ssh in iam (park it in awsmobile acct)
edit ssh/config
chmod 600 ssh/config

git clone ssh://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/jiojiome-mobile-app


chmod  600 ~/.ssh/config 
enghwa:~/environment $ git clone ssh://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/jiojiome-mobile-app
Cloning into 'jiojiome-mobile-app'...
The authenticity of host 'git-codecommit.ap-southeast-1.amazonaws.com (54.240.226.213)' can't be established.
RSA key fingerprint is SHA256:ZIsVa7OVzxrTIf+Rk4UbhPv6Es22mSB3uTBojfPXIno.
RSA key fingerprint is MD5:65:e5:27:c3:09:68:0d:8e:b7:6d:94:25:80:3e:93:cf.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'git-codecommit.ap-southeast-1.amazonaws.com,54.240.226.213' (RSA) to the list of known hosts.
warning: You appear to have cloned an empty repository.
enghwa:~/environment $ cd jiojiome-mobile-app/
enghwa:~/environment/jiojiome-mobile-app (master) $ 
